name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install trivy
      run: | 
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.41.0/trivy_0.41.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.41.0_Linux-64bit.deb

    - name: Trivy scan for code repo
      run: |
        mkdir -p trivy-reports
        trivy fs --exit-code 1 --severity CRITICAL,HIGH --output trivy-reports/report.txt .
    
    - name: Upload Trivy report artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-reports/report.txt

    - name: Loginng into VM
      env: 
        PRIVATE_KEY: ${{ secrets.SSH_PEM_KEY }}
        HOSTNAME: ${{secrets.SSH_HOST}}
        USER_NAME: ${{secrets.USER_NAME}}

      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-${HOSTNAME}.ap-south-1.compute.amazonaws.com
      
    - name: Run Python code
      run: |
        source myenv/bin/activate
        PYTHONPATH=. python apps/user_app/app.py
